### ISSUE TITLE
What to do about tabs in code editor...

### ISSUE THREAD

**Issue by schnej7** [Briefcase/Briefcase#28]
You can use JavaScript to capture the event, prevent the default action (so that the cursor does not shift focus) and insert a tab character.  This however may not preserve the undo stack...

But, disabling the default behavior makes it impossible to move the focus out of the text area without using a mouse. Blind users interact with web pages using the keyboard and nothing else -- they can't see the mouse pointer to do anything useful with it, so it's keyboard or nothing. The tab key is the primary way to navigate the document, and especially forms. Overriding the default behavior of the tab key will make it impossible for blind users to move the focus to the next form element.

So, if you're writing a web site for a broad audience, I'd recommend against doing this without a compelling reason, and provide some kind of alternative for blind users that doesn't trap them in the textarea.

**Comment by schnej7** [comment]
If you are dead set on doing it, this website kind of does it in their code editor http://jsfiddle.net/LJBnU/1/ but it's kind of shaky and doesn't preserve the cursor position on multiple tabs.  Also, they implemented their own undo stack and it looks like it will be a lot of work.

**Comment by AsherGlick** [comment]
I think that tabbing is a crucial part of a code editor, it should not be excluded from the code editor. If a new method needs to be made regardless of whether we choose to keep or remove tabs (either changing the way you tab in a document or changing the way to navigate around the document via the keyboard) then I would say to capture tabs when the text editor is in focus, use `esc` to break focus.

**Comment by schnej7** [comment]
Tabbing is implemented
