### ISSUE TITLE
Renaming a spreadsheet and hitting cancel renames spreadsheet to 'null'.

### ISSUE THREAD

**Issue by joshdk** [Briefcase/Briefcase#34]
When renaming a spreadsheet, if you hit [esc] or click cancel in the `prompt()` dialogue, the spreadsheet will rename to `null`.

The `null` name persists across page reloads.

**Comment by aweinstock314** [comment]
Fixed in commit fe2c226bff6b2ee7052abfdefc89e86dec364e2e.
