### ISSUE TITLE
Spreadsheet selection does not draw transparent overlay in selection area

### ISSUE THREAD

**Issue by akarnani** [Briefcase/Briefcase#9]

**Comment by AsherGlick** [comment]
I have tried this in chromium as well as in firefox and the transparent layer does appear, check to make sure that this is still a bug. Quite possibly it is a cross-operating system bug.

**Comment by akarnani** [comment]
This appears fixed to me.  Perhaps it was related to another seemingly innocuous JS error?

Closing because we can no longer reproduce.
